-- Fix: Reset PATCH-024 in schema_patch_history so it re-runs
-- and updates notifications_type_check with BOOKING_MENTOR_COMPLETED
-- Then re-apply the constraint directly

-- Step 1: Reset patch history so PATCH-024 re-runs on next app start
DELETE FROM schema_patch_history WHERE patch_key = 'PATCH-024-short-term-job-notification-types';
RAISE NOTICE 'Reset PATCH-024 from schema_patch_history';

-- Step 2: Immediately fix the constraint now
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
CHECK (type IN (
    'LIKE','COMMENT','PREMIUM_PURCHASE','WALLET_DEPOSIT','COIN_PURCHASE',
    'WELCOME','PREMIUM_EXPIRATION','PREMIUM_CANCEL','SYSTEM','WARNING',
    'VIOLATION_REPORT','BOOKING_CREATED','BOOKING_CONFIRMED','BOOKING_REJECTED',
    'BOOKING_REMINDER','BOOKING_COMPLETED','BOOKING_CANCELLED','BOOKING_REFUND',
    'BOOKING_STARTED','BOOKING_MENTOR_COMPLETED',
    'PRECHAT_MESSAGE','RECRUITMENT_MESSAGE','MENTOR_REVIEW_RECEIVED',
    'WITHDRAWAL_APPROVED','WITHDRAWAL_REJECTED','MENTOR_LEVEL_UP',
    'MENTOR_BADGE_AWARDED','TASK_DEADLINE','TASK_OVERDUE','TASK_REVIEW',
    'ASSIGNMENT_SUBMITTED','ASSIGNMENT_GRADED','ASSIGNMENT_LATE',
    'COURSE_REJECTED','COURSE_SUSPENDED','COURSE_RESTORED',
    'JOB_APPROVED','JOB_REJECTED','JOB_DELETED','JOB_BANNED','JOB_UNBANNED',
    'ESCROW_FUNDED','ESCROW_RELEASED','ESCROW_REFUNDED',
    'DISPUTE_OPENED','DISPUTE_RESOLVED','REVIEW_WINDOW_EXPIRING'
));
RAISE NOTICE 'Fixed notifications_type_check constraint with all notification types';
