spring:
  datasource:
    url: jdbc:postgresql://221.132.33.141:5432/skillverse_db
    username: skillverse_user
    password: ${DB_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: none  # Don't modify existing schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:skillverseexe@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:fgbx gygh iglz dcou}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  jackson:
    time-zone: ${SPRING_JACKSON_TIME_ZONE:Asia/Ho_Chi_Minh}
    date-format: ${SPRING_JACKSON_DATE_FORMAT:yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}
    
server:
  port: ${SERVER_PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
jwt:
  secret: ${JWT_SECRET:test-secret-key-for-junit-tests-only-1234567890123456}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300}   # from env or default 5 minutes
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:600}  # from env or default 10 minutes

email:
  from: ${EMAIL_FROM:skillverseexe@gmail.com}
  from-name: ${EMAIL_FROM_NAME:SkillVerse}
  templates:
    base-url: "http://localhost:8080"

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}
    
logging:
  level:
    com.exe.skillverse_backend: INFO
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR