package com.exe.skillverse_backend.notification_service.entity;

public enum NotificationType {
    LIKE,
    COMMENT,
    PREMIUM_PURCHASE,
    WALLET_DEPOSIT,
    COIN_PURCHASE,
    WELCOME,
    PREMIUM_EXPIRATION,
    PREMIUM_CANCEL,
    SYSTEM,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_REJECTED,
    BOOKING_REMINDER,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    BOOKING_REFUND,
    PRECHAT_MESSAGE,
    MENTOR_REVIEW_RECEIVED,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    MENTOR_LEVEL_UP,
    MENTOR_BADGE_AWARDED
}
