package com.exe.skillverse_backend.shared.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
  // 4xx
  BAD_REQUEST(HttpStatus.BAD_REQUEST, "BAD_REQUEST"),
  UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
  FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
  NOT_FOUND(HttpStatus.NOT_FOUND, "NOT_FOUND"),
  CONFLICT(HttpStatus.CONFLICT, "CONFLICT"),
  VALIDATION_FAILED(HttpStatus.UNPROCESSABLE_ENTITY, "VALIDATION_FAILED"),
  
  // Premium/Subscription specific
  USAGE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "USAGE_LIMIT_EXCEEDED"),
  SUBSCRIPTION_NOT_FOUND(HttpStatus.NOT_FOUND, "SUBSCRIPTION_NOT_FOUND"),
  SUBSCRIPTION_ALREADY_ACTIVE(HttpStatus.CONFLICT, "SUBSCRIPTION_ALREADY_ACTIVE"),
  INSUFFICIENT_BALANCE(HttpStatus.PAYMENT_REQUIRED, "INSUFFICIENT_BALANCE"),
  PLAN_NOT_AVAILABLE(HttpStatus.GONE, "PLAN_NOT_AVAILABLE"),

  // Job Boost specific
  JOB_BOOST_NOT_FOUND(HttpStatus.NOT_FOUND, "JOB_BOOST_NOT_FOUND"),
  JOB_BOOST_EXPIRED(HttpStatus.GONE, "JOB_BOOST_EXPIRED"),
  JOB_BOOST_ALREADY_ACTIVE(HttpStatus.CONFLICT, "JOB_BOOST_ALREADY_ACTIVE"),
  JOB_BOOST_QUOTA_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "JOB_BOOST_QUOTA_EXCEEDED"),
  JOB_BOOST_INVALID_STATUS(HttpStatus.BAD_REQUEST, "JOB_BOOST_INVALID_STATUS"),

  // Candidate Search specific
  CANDIDATE_SEARCH_ACCESS_DENIED(HttpStatus.FORBIDDEN, "CANDIDATE_SEARCH_ACCESS_DENIED"),
  AI_MATCHING_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "AI_MATCHING_UNAVAILABLE"),
  CANDIDATE_NOT_FOUND(HttpStatus.NOT_FOUND, "CANDIDATE_NOT_FOUND"),

  // 5xx
  INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR"),
  SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "SERVICE_UNAVAILABLE");

  public final HttpStatus status;
  public final String code;

  ErrorCode(HttpStatus status, String code) {
    this.status = status;
    this.code = code;
  }
}
